/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversisuhu;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import mainmenu.MainMenu;

/**
 *
 * @author acer
 */
public class KonversiAllSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu
     */
    public KonversiAllSuhu() {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupInput = new javax.swing.ButtonGroup();
        buttonGroupOutput = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        textInput = new javax.swing.JTextField();
        panelSuhuInput = new javax.swing.JPanel();
        inputCelciusRadioButton = new javax.swing.JRadioButton();
        inputFahrenheitRadioButton = new javax.swing.JRadioButton();
        inputKelvinRadioButton = new javax.swing.JRadioButton();
        inputReamurRadioButton = new javax.swing.JRadioButton();
        panel2 = new javax.swing.JPanel();
        outputLabel = new javax.swing.JLabel();
        panelSuhuOutput = new javax.swing.JPanel();
        outputCelciusRadioButton = new javax.swing.JRadioButton();
        outputFahrenheitRadioButton = new javax.swing.JRadioButton();
        outputKelvinRadioButton = new javax.swing.JRadioButton();
        outputReamurRadioButton = new javax.swing.JRadioButton();
        textOutput = new javax.swing.JTextField();
        panel3 = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        exitButton1 = new javax.swing.JButton();
        convertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Aplikasi Konversi Suhu");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        mainPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2), "Konversi Suhu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        mainPanel.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        panel1.setBackground(new java.awt.Color(153, 244, 175));
        panel1.setForeground(new java.awt.Color(153, 244, 175));

        inputLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        inputLabel.setForeground(new java.awt.Color(0, 0, 0));
        inputLabel.setText("Celcius");

        textInput.setBackground(new java.awt.Color(255, 255, 255));
        textInput.setForeground(new java.awt.Color(0, 0, 0));
        textInput.setBorder(new javax.swing.border.MatteBorder(null));
        textInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInputActionPerformed(evt);
            }
        });
        textInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textInputKeyTyped(evt);
            }
        });

        panelSuhuInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));
        panelSuhuInput.setLayout(new java.awt.GridLayout(0, 1));

        inputCelciusRadioButton.setBackground(new java.awt.Color(153, 244, 175));
        buttonGroupInput.add(inputCelciusRadioButton);
        inputCelciusRadioButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        inputCelciusRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        inputCelciusRadioButton.setText("Celcius");
        panelSuhuInput.add(inputCelciusRadioButton);

        inputFahrenheitRadioButton.setBackground(new java.awt.Color(153, 244, 175));
        buttonGroupInput.add(inputFahrenheitRadioButton);
        inputFahrenheitRadioButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        inputFahrenheitRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        inputFahrenheitRadioButton.setText("Fahrenheit");
        panelSuhuInput.add(inputFahrenheitRadioButton);

        inputKelvinRadioButton.setBackground(new java.awt.Color(153, 244, 175));
        buttonGroupInput.add(inputKelvinRadioButton);
        inputKelvinRadioButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        inputKelvinRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        inputKelvinRadioButton.setText("Kelvin");
        panelSuhuInput.add(inputKelvinRadioButton);

        inputReamurRadioButton.setBackground(new java.awt.Color(153, 244, 175));
        buttonGroupInput.add(inputReamurRadioButton);
        inputReamurRadioButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        inputReamurRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        inputReamurRadioButton.setText("Reamur");
        panelSuhuInput.add(inputReamurRadioButton);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(panelSuhuInput, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLabel))
                .addGap(42, 42, 42))
            .addComponent(panelSuhuInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(panel1);

        panel2.setBackground(new java.awt.Color(255, 221, 243));
        panel2.setForeground(new java.awt.Color(255, 221, 243));

        outputLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(0, 0, 0));
        outputLabel.setText("Fahrenheit");

        panelSuhuOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));
        panelSuhuOutput.setLayout(new java.awt.GridLayout(0, 1));

        outputCelciusRadioButton.setBackground(new java.awt.Color(255, 221, 243));
        buttonGroupOutput.add(outputCelciusRadioButton);
        outputCelciusRadioButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        outputCelciusRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        outputCelciusRadioButton.setText("Celcius");
        panelSuhuOutput.add(outputCelciusRadioButton);

        outputFahrenheitRadioButton.setBackground(new java.awt.Color(255, 221, 243));
        buttonGroupOutput.add(outputFahrenheitRadioButton);
        outputFahrenheitRadioButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        outputFahrenheitRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        outputFahrenheitRadioButton.setText("Fahrenheit");
        panelSuhuOutput.add(outputFahrenheitRadioButton);

        outputKelvinRadioButton.setBackground(new java.awt.Color(255, 221, 243));
        buttonGroupOutput.add(outputKelvinRadioButton);
        outputKelvinRadioButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        outputKelvinRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        outputKelvinRadioButton.setText("Kelvin");
        panelSuhuOutput.add(outputKelvinRadioButton);

        outputReamurRadioButton.setBackground(new java.awt.Color(255, 221, 243));
        buttonGroupOutput.add(outputReamurRadioButton);
        outputReamurRadioButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        outputReamurRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        outputReamurRadioButton.setText("Reamur");
        panelSuhuOutput.add(outputReamurRadioButton);

        textOutput.setBackground(new java.awt.Color(255, 255, 255));
        textOutput.setForeground(new java.awt.Color(0, 0, 0));
        textOutput.setBorder(new javax.swing.border.MatteBorder(null));
        textOutput.setEnabled(false);
        textOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOutputActionPerformed(evt);
            }
        });
        textOutput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textOutputKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(textOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(panelSuhuOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuhuOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputLabel))
                .addGap(42, 42, 42))
        );

        mainPanel.add(panel2);

        panel3.setBackground(new java.awt.Color(255, 255, 204));

        clearButton.setBackground(new java.awt.Color(204, 204, 255));
        clearButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 0, 0));
        clearButton.setText("Clear");
        clearButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton1.setBackground(new java.awt.Color(204, 204, 255));
        exitButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        exitButton1.setForeground(new java.awt.Color(0, 0, 0));
        exitButton1.setText("Exit");
        exitButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        convertButton.setBackground(new java.awt.Color(204, 204, 255));
        convertButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        convertButton.setForeground(new java.awt.Color(0, 0, 0));
        convertButton.setText("Convert");
        convertButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        mainPanel.add(panel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(402, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    double hasil;
    
    private void selectInputCelcius(){
        if (inputCelciusRadioButton.isSelected() && outputCelciusRadioButton.isSelected()) {
            inputLabel.setText("Celcius");
            outputLabel.setText("Celcius");
            hasil = Double.parseDouble(textInput.getText());
            textOutput.setText(String.valueOf(String.format("%.2f",hasil)));
        } else if (inputCelciusRadioButton.isSelected() && outputFahrenheitRadioButton.isSelected()) {
            inputLabel.setText("Celcius");
            outputLabel.setText("Fahrenheit");
            hasil = (Double.parseDouble(textInput.getText()) * 1.8) + 32;
            textOutput.setText(String.valueOf(String.format("%.2f",hasil)));
        } else if (inputCelciusRadioButton.isSelected() && outputKelvinRadioButton.isSelected()) {
            inputLabel.setText("Celcius");
            outputLabel.setText("Kelvin");
            hasil = (Double.parseDouble(textInput.getText()) + 273.15);
            textOutput.setText(String.valueOf(String.format("%.2f",hasil)));
        } else if (inputCelciusRadioButton.isSelected() && outputReamurRadioButton.isSelected()) {
            inputLabel.setText("Celcius");
            outputLabel.setText("Reamur");
            hasil = (Double.parseDouble(textInput.getText()) * 0.8);
            textOutput.setText(String.valueOf(String.format("%.2f",hasil)));
        } 
    }
    
    private void selectInputFahrenheit(){
        if (inputFahrenheitRadioButton.isSelected() && outputCelciusRadioButton.isSelected()) {
            inputLabel.setText("Fahrenheit");
            outputLabel.setText("Celcius");
            hasil = (Double.parseDouble(textInput.getText()) - 32) / 1.8;
            textOutput.setText(String.valueOf(String.format("%.2f",hasil)));
        } else if (inputFahrenheitRadioButton.isSelected() && outputFahrenheitRadioButton.isSelected()) {
            inputLabel.setText("Fahrenheit");
            outputLabel.setText("Fahrenheit");
            hasil = Double.parseDouble(textInput.getText());
            textOutput.setText(String.valueOf(String.format("%.2f",hasil)));
        } else if (inputFahrenheitRadioButton.isSelected() && outputKelvinRadioButton.isSelected()) {
            inputLabel.setText("Fahrenheit");
            outputLabel.setText("Kelvin");
            hasil = (Double.parseDouble(textInput.getText()) + 459.67) / 1.8;
            textOutput.setText(String.valueOf(String.format("%.2f",hasil)));
        } else if (inputFahrenheitRadioButton.isSelected() && outputReamurRadioButton.isSelected()) {
            inputLabel.setText("Fahrenheit");
            outputLabel.setText("Reamur");
            hasil = (Double.parseDouble(textInput.getText()) - 32) / 2.25;
            textOutput.setText(String.valueOf(String.format("%.2f",hasil)));
        } 
    }
    
    private void selectInputKelvin(){
        if (inputKelvinRadioButton.isSelected() && outputCelciusRadioButton.isSelected()) {
            inputLabel.setText("Kelvin");
            outputLabel.setText("Celcius");
            hasil = Double.parseDouble(textInput.getText()) - 273.15;
            textOutput.setText(String.valueOf(String.format("%.2f", hasil)));
        } else if (inputKelvinRadioButton.isSelected() && outputFahrenheitRadioButton.isSelected()) {
            inputLabel.setText("Kelvin");
            outputLabel.setText("Fahrenheit");
            hasil = (Double.parseDouble(textInput.getText()) * 1.8) - 459.67;
            textOutput.setText(String.valueOf(String.format("%.2f", hasil)));
        } else if (inputKelvinRadioButton.isSelected() && outputKelvinRadioButton.isSelected()) {
            inputLabel.setText("Kelvin");
            outputLabel.setText("Kelvin");
            hasil = Double.parseDouble(textInput.getText());
            textOutput.setText(String.valueOf(String.format("%.2f", hasil)));
        } else if (inputKelvinRadioButton.isSelected() && outputReamurRadioButton.isSelected()) {
            inputLabel.setText("Kelvin");
            outputLabel.setText("Reamur");
            hasil = (Double.parseDouble(textInput.getText()) - 273.15) * 0.8;
            textOutput.setText(String.valueOf(String.format("%.2f", hasil)));
        } 
    }
    
   private void selectInputReamur(){
       if (inputReamurRadioButton.isSelected() && outputCelciusRadioButton.isSelected()) {
           inputLabel.setText("Reamur");
           outputLabel.setText("Celcius");
           hasil = Double.parseDouble(textInput.getText()) / 0.8;
           textOutput.setText(String.valueOf(String.format("%.2f", hasil)));
       } else if (inputReamurRadioButton.isSelected() && outputFahrenheitRadioButton.isSelected()) {
           inputLabel.setText("Reamur");
           outputLabel.setText("Fahrenheit");
           hasil = (Double.parseDouble(textInput.getText()) - 7.5) * 24 / 7 +32;
           textOutput.setText(String.valueOf(String.format("%.2f", hasil)));
       } else if (inputReamurRadioButton.isSelected() && outputKelvinRadioButton.isSelected()) {
           inputLabel.setText("Reamur");
           outputLabel.setText("Kelvin");
           hasil = (Double.parseDouble(textInput.getText()) / 0.8) + 273.15;
           textOutput.setText(String.valueOf(String.format("%.2f", hasil)));
       } else if (inputReamurRadioButton.isSelected() && outputReamurRadioButton.isSelected()) {
           inputLabel.setText("Reamur");
           outputLabel.setText("Reamur");
           hasil = Double.parseDouble(textInput.getText());
           textOutput.setText(String.valueOf(String.format("%.2f", hasil)));
       } 
   } 
   
   private void setSelected(){
       //inputCelciusRadioButton.setSelected(true);
       //outputCelciusRadioButton.setSelected(true);
       buttonGroupInput.clearSelection();
       buttonGroupOutput.clearSelection();
       textInput.setText("");
       textOutput.setText("");
       inputLabel.setText("");
       outputLabel.setText("");
   }
    
    private void textInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textInputActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
        if ( (inputCelciusRadioButton.isSelected() || inputFahrenheitRadioButton.isSelected()
              || inputKelvinRadioButton.isSelected() || inputReamurRadioButton.isSelected())
              && (outputCelciusRadioButton.isSelected() || outputFahrenheitRadioButton.isSelected()
              || outputKelvinRadioButton.isSelected() || outputReamurRadioButton.isSelected()) ) {
            
            if (textInput.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "MASUKAN NILAI SUHU !!", "EROR" , JOptionPane.ERROR_MESSAGE);
            }else{
                selectInputCelcius();
                selectInputFahrenheit();
                selectInputKelvin();
                selectInputReamur();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "PILIH SATUAN SUHU !!", "EROR" , JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_convertButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        setSelected();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void textInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textInputKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (! ((Character.isDigit(c)||
                (c == KeyEvent.VK_BACKSPACE)||
                (c == KeyEvent.VK_DELETE)||
                (c == KeyEvent.VK_ENTER )||
                (c == KeyEvent.VK_PERIOD))
               )) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Masukan Suhu Dengan Benar");
            evt.consume();
        }
    }//GEN-LAST:event_textInputKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        setSelected();
    }//GEN-LAST:event_formWindowActivated

    private void textOutputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textOutputKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textOutputKeyTyped

    private void textOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textOutputActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiAllSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiAllSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiAllSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiAllSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiAllSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupInput;
    private javax.swing.ButtonGroup buttonGroupOutput;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton convertButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JRadioButton inputCelciusRadioButton;
    private javax.swing.JRadioButton inputFahrenheitRadioButton;
    private javax.swing.JRadioButton inputKelvinRadioButton;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JRadioButton inputReamurRadioButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton outputCelciusRadioButton;
    private javax.swing.JRadioButton outputFahrenheitRadioButton;
    private javax.swing.JRadioButton outputKelvinRadioButton;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JRadioButton outputReamurRadioButton;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panelSuhuInput;
    private javax.swing.JPanel panelSuhuOutput;
    private javax.swing.JTextField textInput;
    private javax.swing.JTextField textOutput;
    // End of variables declaration//GEN-END:variables
}
